on: [ push ]
jobs:
  integration:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - id: forgejo
        uses: https://code.forgejo.org/actions/setup-forgejo@v1
        with:
          user: testuser
          password: admin1234
          image-version: 1.19
      - name: 001
        run: |
          set -ex
          export FORGEJO_RUNNER_LOGS="${{ steps.forgejo.outputs.runner-logs }}"
          forgejo-test-helper.sh push_self_action http://testuser:admin1234@${{ steps.forgejo.outputs.host-port }} testuser forgejo-release vTest
          forgejo-test-helper.sh run_workflow testdata/nested-upload-download http://testuser:admin1234@${{ steps.forgejo.outputs.host-port }} testuser nested-upload-download forgejo-release
      - name: 002
        run: |
          set -ex
          export FORGEJO="${{ steps.forgejo.outputs.url }}"
          export TOKEN="${{ steps.forgejo.outputs.token }}"
          export DOER=testuser
          export VERBOSE=true
          testdata/forgejo-release-test.sh test_run testuser otherrepo
