on: [ push ]
jobs:
  integration:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - id: forgejo
        uses: https://code.forgejo.org/actions/setup-forgejo@v1
        with:
          user: testuser
          password: admin1234
          image-version: 1.19
      - name: 001
        run: |
          export FORGEJO_RUNNER_LOGS="${{ steps.forgejo.outputs.runner-logs }}"
          testdata/run.sh push_self http://testuser:admin1234@${{ steps.forgejo.outputs.host-port }} testuser setup-forgejo-release
          testdata/run.sh workflow http://testuser:admin1234@${{ steps.forgejo.outputs.host-port }} testuser try-setup-forgejo-release
      - name: 002
        run: |
          set -ex
          curl -sS ${{ steps.forgejo.outputs.url }}/api/forgejo/v1/version | grep 1.19
          export FORGEJO="${{ steps.forgejo.outputs.url }}"
          export RELEASETEAMTOKEN="${{ steps.forgejo.outputs.token }}"
          export CI_REPO_OWNER=testuser
          testdata/forgejo-release-test.sh test_run
