on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: docker

    steps:
      # needs to be in a different dir, so binary and rna cache don't conflict
      - uses: https://data.forgejo.org/actions/checkout@v6
        with:
          path: forgejo-release

      - name: publish release
        uses: ./forgejo-release
        with:
          direction: upload
          override: ${{ vars.OVERRIDE || 'false' }}
          verbose: ${{ vars.VERBOSE || 'false' }}
          release-notes-assistant: true
          skip-assets: true
