on: [ pull_request, push ]
jobs:
  integration:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4

      - name: Unit tests of the supporting script forgejo-release.sh
        run: |
          testdata/forgejo-release-test.sh test_system_tea_bin
          testdata/forgejo-release-test.sh test_download_tea_bin
          testdata/forgejo-release-test.sh test_maybe_sign_release